### ISSUE TITLE
本地怎么运行需要的node版本是多少 windows

### ISSUE THREAD

**Issue by zhang4881820** [Snailclimb/JavaGuide#1824]
require() of ES modules is not supported.
require() of D:\source-study\JavaGuide\node_modules\vuepress-theme-hope\lib\node\index.js from D:\source-study\JavaGuide\docs\.vuepress\themeConfig.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
.
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (D:\source-study\JavaGuide\docs\.vuepress\themeConfig.ts:23:34)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.require.extensions..ts (D:\source-study\JavaGuide\node_modules\vuepress-vite\node_modules\@vuepress\cli\lib\utils\allowTs.js:11:11)
    at Module.load (internal/modules/cjs/loader.js:985:32)

**Comment by Snailclimb** [comment]
这是我本地的版本：

```bash
❯ npm -v
8.3.1
❯ vuepress -v

   ╭───────────────────────────────────────────╮
   │                                           │
   │      Update available 1.8.2 → 1.9.7       │
   │   Run npm i -g @vuepress/core to update   │
   │                                           │
   ╰───────────────────────────────────────────╯
```
